server:
  port: 9050
spring:
  application:
    name: product-app
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:33060/fusion_product
    username: fishep
    password: fishep
    driver-class-name: com.mysql.cj.jdbc.Driver