server:
  port: 9020
spring:
  application:
    name: order-app
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:33060/fusion_order
    username: fishep
    password: fishep
    driver-class-name: com.mysql.cj.jdbc.Driver