spring:
  datasource:
    url: jdbc:mysql://localhost:33060/fusion_product
    username: fishep
    password: fishep
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 63790
    password:
    ssl: false
    database: 0