server:
  port: 9000
spring:
  application:
    name: common-app
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63790}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
    database: ${REDIS_DATABASE:0}